export const clientes = [
    {
      sucursal: "Sucursal 1",
      barbero: "Juan Pérez",
      cliente: "Carlos López",
      telefono: "011-23456789",
      servicio: "Corte de cabello",
      fecha: "2025-01-29",
      metodo_pago: "Efectivo",
      estado_pago: "Pagado",
      monto: "1500",
    },
    {
      sucursal: "Sucursal 2",
      barbero: "Ana Gómez",
      cliente: "Lucía Ramírez",
      telefono: "011-98765432",
      servicio: "Corte y barba",
      fecha: "2025-01-28",
      metodo_pago: "Tarjeta",
      estado_pago: "Pendiente",
      monto: "2500",
    },
    {
      sucursal: "Sucursal 3",
      barbero: "Marcos Silva",
      cliente: "Pedro Martínez",
      telefono: "011-34567890",
      servicio: "Corte de cabello",
      fecha: "2025-01-27",
      metodo_pago: "Transferencia",
      estado_pago: "Pagado",
      monto: "1800",
    },
  ];
